/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author faysal
 */
import DeleteFromDatabase.DeletePanelFrontEnd;
import DeleteFromDatabase.setList;
import SetList.SetList;
import createDatabase.CreateDatabase;
import createDatabase.DatabaseExistence;
import createDatabase.GetDataFromDatabase;
import createDatabase.InsertIntoDatabase;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class FrontEnd extends javax.swing.JFrame {

    /**
     * Creates new form FrontEnd
     */
    boolean isDatabaseCreated;
    
    SetList SL;
    
    DatabaseExistence obDatabaseExistence=new DatabaseExistence();
    DefaultListModel dfm=new DefaultListModel();
    
   
    public FrontEnd() {
        

        
        
        initComponents();
        
        // Find that database is existed or not............
        
        
        isDatabaseCreated= obDatabaseExistence.dbExist();
        ResetButton.setEnabled(isDatabaseCreated);
        
        
         
        if(isDatabaseCreated){
        String createdDB="Database Created.. Press Insert to add Item.";
                    
        dfm.addElement(createdDB);
                    
        jList1.setModel(dfm);
        }
        
        /*
        jList1.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
            
                String urlString= (String) jList1.getSelectedValue();
            
                
                if(!e.getValueIsAdjusting()) {
                    System.out.println("URL IS : "+urlString);
                }
                
                
            }
        });
        
        
        */
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        INSERT = new javax.swing.JButton();
        DeleteFrontEnd = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        RefreshFontEnd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WebsiteAddressNoteBook ");
        setIconImage(new ImageIcon(getClass().getResource("/icons/icon1.jpg")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<: Enter to search :>");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "< NO DATABASE >" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<: Enter on keyword :>");

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_Button_Event(evt);
            }
        });
        jPanel4.add(A);

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Button_Event(evt);
            }
        });
        jPanel4.add(B);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_Button_Event(evt);
            }
        });
        jPanel4.add(C);

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_Button_Event(evt);
            }
        });
        jPanel4.add(D);

        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_Button_Event(evt);
            }
        });
        jPanel4.add(E);

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_Button_Event(evt);
            }
        });
        jPanel4.add(F);

        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_Button_Event(evt);
            }
        });
        jPanel4.add(G);

        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_Button_Event(evt);
            }
        });
        jPanel4.add(H);

        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_Button_Event(evt);
            }
        });
        jPanel4.add(I);

        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_Button_Event(evt);
            }
        });
        jPanel4.add(J);

        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_Button_Event(evt);
            }
        });
        jPanel4.add(K);

        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_Button_Event(evt);
            }
        });
        jPanel4.add(L);

        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Button_Event(evt);
            }
        });
        jPanel4.add(M);

        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_Button_Event(evt);
            }
        });
        jPanel4.add(N);

        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_Button_Event(evt);
            }
        });
        jPanel4.add(O);

        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_Button_Event(evt);
            }
        });
        jPanel4.add(P);

        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_Button_Event(evt);
            }
        });
        jPanel4.add(Q);

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Button_Event(evt);
            }
        });
        jPanel4.add(R);

        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_Button_Event(evt);
            }
        });
        jPanel4.add(S);

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_Button_Event(evt);
            }
        });
        jPanel4.add(T);

        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_Button_Event(evt);
            }
        });
        jPanel4.add(U);

        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_Button_Event(evt);
            }
        });
        jPanel4.add(V);

        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W_Button_Event(evt);
            }
        });
        jPanel4.add(W);

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_Button_Event(evt);
            }
        });
        jPanel4.add(X);

        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y_Button_Event(evt);
            }
        });
        jPanel4.add(Y);

        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z_Button_Event(evt);
            }
        });
        jPanel4.add(Z);

        INSERT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        INSERT.setText("INSERT");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });

        DeleteFrontEnd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteFrontEnd.setText("DELETE");
        DeleteFrontEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFrontEndActionPerformed(evt);
            }
        });

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton29.setText("ALL");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ResetButton.setText("RESET");
        ResetButton.setEnabled(false);
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        RefreshFontEnd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RefreshFontEnd.setText("REFRESH");
        RefreshFontEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshFontEndActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("SAVE as FILE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RefreshFontEnd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(INSERT)
                                    .addGap(132, 132, 132)
                                    .addComponent(DeleteFrontEnd))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INSERT)
                    .addComponent(DeleteFrontEnd))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29)
                    .addComponent(ResetButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshFontEnd)
                    .addComponent(jButton2))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setMnemonic('X');
        jMenuItem1.setText("EXIT");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        // TODO add your handling code here:
        
        if(isDatabaseCreated==false)
        {
            int getIntValue= JOptionPane.showConfirmDialog(rootPane, "Database is not created ! Do you"
                + " want to create it? ");
         
            System.out.println(getIntValue);
         
        
            if(getIntValue==0){
            
                createDatabase.CreateDatabase objCD=new CreateDatabase();
                
                objCD.createDatabaseMethod();
                DatabaseExistence dbe=new DatabaseExistence();
                
                if(dbe.dbExist()) {
                    isDatabaseCreated=true;
                    
                    ResetButton.setEnabled(isDatabaseCreated);
                    String createdDB="Database Created.. Press Insert to add Item.";
                    
                     dfm.addElement(createdDB);
            
                     jList1.setModel(dfm);
                    
                }
                else{
                isDatabaseCreated=false;
                }
            
            }
       
       
        }
        
        else
        {
        
           int getYesValue=JOptionPane.showConfirmDialog(rootPane, "Do you want to insert new website address ? ", "Insert confirmation ?", JOptionPane.YES_NO_OPTION);
        
            if(getYesValue==0)
            {
            
            InsertIntoDatabase obj_CD = new InsertIntoDatabase();
            
            obj_CD.setVisible(true);
            obj_CD.setLocationRelativeTo(null);
            }
            
        
        }
        
    }//GEN-LAST:event_INSERTActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        GetDataFromDatabase objgdfd=new GetDataFromDatabase();
                String getWebAdd[]= objgdfd.getWNFromDB();
                int lengthofid=objgdfd.totalID(getWebAdd);
                if(lengthofid!=0){
                    DefaultListModel dlm=new DefaultListModel();
                
                     for(String wan: getWebAdd)
                        {
                            if(wan!=null) {
                                    dlm.addElement(wan);
                                }
                        }
                
                         jList1.setModel(dlm);
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel dlmreset=new DefaultListModel();
        
        jList1.setModel(dlmreset);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        SL=new SetList();
        String getInput=jTextField1.getText().toUpperCase();
        
        
        
        if(!getInput.equals("")){
        
            DefaultListModel dlml= SL.CheckAndMakeList(getInput);
        
            int length=dlml.getSize();
        
       
            System.out.println("Size of dlml is : "+length);
        
            if(length==0)
        
            {
           
                JOptionPane.showMessageDialog(rootPane, "Sorry.. No Item Found !", "No Item !", JOptionPane.INFORMATION_MESSAGE);
        
                jTextField1.setText("");
            }
        
            else{
           
                jList1.setModel(dlml);
        
                JOptionPane.showMessageDialog(rootPane, length+" Items Found .", "Found Item !", JOptionPane.INFORMATION_MESSAGE);
            
                jTextField1.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Sorry.. You've to insert at least one letter ..!", "Error input !", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void A_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_Button_Event
  
        SearchWA(A.getText());
    }//GEN-LAST:event_A_Button_Event

    private void B_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Button_Event
       SearchWA(B.getText());
    }//GEN-LAST:event_B_Button_Event

    private void C_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_Button_Event
        SearchWA(C.getText());
    }//GEN-LAST:event_C_Button_Event

    private void D_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_Button_Event
        SearchWA(D.getText());
    }//GEN-LAST:event_D_Button_Event

    private void E_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_Button_Event
        SearchWA(E.getText());
    }//GEN-LAST:event_E_Button_Event

    private void F_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_Button_Event
        SearchWA(F.getText());
    }//GEN-LAST:event_F_Button_Event

    private void G_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_Button_Event
        SearchWA(G.getText());
    }//GEN-LAST:event_G_Button_Event

    private void H_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_Button_Event
        SearchWA(H.getText());
    }//GEN-LAST:event_H_Button_Event

    private void I_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_Button_Event
        SearchWA(I.getText());
    }//GEN-LAST:event_I_Button_Event

    private void J_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_Button_Event
        SearchWA(J.getText());
    }//GEN-LAST:event_J_Button_Event

    private void K_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_Button_Event
        SearchWA(K.getText());
    }//GEN-LAST:event_K_Button_Event

    private void L_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_Button_Event
        SearchWA(L.getText());
    }//GEN-LAST:event_L_Button_Event

    private void M_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Button_Event
        SearchWA(M.getText());
    }//GEN-LAST:event_M_Button_Event

    private void N_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_Button_Event
        SearchWA(N.getText());
    }//GEN-LAST:event_N_Button_Event

    private void O_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_Button_Event
        SearchWA(O.getText());
    }//GEN-LAST:event_O_Button_Event

    private void P_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_Button_Event
        SearchWA(P.getText());
    }//GEN-LAST:event_P_Button_Event

    private void Q_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_Button_Event
        SearchWA(Q.getText());
    }//GEN-LAST:event_Q_Button_Event

    private void R_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Button_Event
        SearchWA(R.getText());
    }//GEN-LAST:event_R_Button_Event

    private void S_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_Button_Event
        SearchWA(S.getText());
    }//GEN-LAST:event_S_Button_Event

    private void T_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_Button_Event
        SearchWA(T.getText());
    }//GEN-LAST:event_T_Button_Event

    private void U_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_Button_Event
        SearchWA(U.getText());
    }//GEN-LAST:event_U_Button_Event

    private void V_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_Button_Event
        SearchWA(V.getText());
    }//GEN-LAST:event_V_Button_Event

    private void W_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W_Button_Event
        SearchWA(W.getText());
    }//GEN-LAST:event_W_Button_Event

    private void X_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_Button_Event
        SearchWA(X.getText());
    }//GEN-LAST:event_X_Button_Event

    private void Y_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y_Button_Event
        SearchWA(Y.getText());
    }//GEN-LAST:event_Y_Button_Event

    private void Z_Button_Event(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z_Button_Event
        SearchWA(Z.getText());
    }//GEN-LAST:event_Z_Button_Event

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try {
            String urlString= (String) jList1.getSelectedValue();
              
            
                    if(!evt.getValueIsAdjusting()) {
                        System.out.println("URL IS : "+urlString);
                    }
                    
                    
                     if(!evt.getValueIsAdjusting()&&(urlString != null)) 
                     {
                         urlString = "http://"+urlString;
                         int getPermission = JOptionPane.showConfirmDialog(rootPane, "Do you want to visit that link?", "Visit Permission ?", JOptionPane.YES_NO_OPTION);
                         if(getPermission==0) {
                             Desktop.getDesktop().browse(new URL(urlString).toURI());
                         }
                      }
                     
        } catch (URISyntaxException | IOException ex) {
        }
                    
    }//GEN-LAST:event_jList1ValueChanged

    private void DeleteFrontEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFrontEndActionPerformed
        // TODO add your handling code here:
        if(isDatabaseCreated){
        DeletePanelFrontEnd objectdfe= new DeletePanelFrontEnd();
        objectdfe.setVisible(true);
        objectdfe.setLocationRelativeTo(null);
        }
        else
        {
        JOptionPane.showMessageDialog(null, "sorry.. no database existed..", "Error..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteFrontEndActionPerformed

    private void RefreshFontEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshFontEndActionPerformed
        // TODO add your handling code here:
          if(obDatabaseExistence.dbExist()){
    
        setList objsetlist=new setList();
        
       jList1.setModel(objsetlist.deleteSetList());
        
    }
    else
    {
    JOptionPane.showMessageDialog(rootPane, "NO DATABASE !", "ERROR !", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RefreshFontEndActionPerformed

    public void SearchWA(String getInput){
    
        SL=new SetList();
        
            DefaultListModel dlml= SL.CheckAndMakeList(getInput);
        
            int length=dlml.getSize();
        
       
            System.out.println("Size of dlml is : "+length);
        
            if(length==0)
        
            {
                JOptionPane.showMessageDialog(rootPane, "Sorry.. No Item Found !", "No Item !", JOptionPane.INFORMATION_MESSAGE);            
            }
        
            else{          
                jList1.setModel(dlml);        
                JOptionPane.showMessageDialog(rootPane, length+" Items Found .", "Found Item !", JOptionPane.INFORMATION_MESSAGE);            
            }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
               FrontEnd frontEnd=new FrontEnd();
               frontEnd.setVisible(true);
               frontEnd.setLocationRelativeTo(null);
               
               
        //       try {
            // BufferedImage bf=new ImageIO.read(getClass().getResource("image/ic2.png"));
             
            // ImageIcon im=new ImageIcon(getClass().getResource("ic.png"));
            // Image img= new
    //    Image im;
         //   im = ImageIO.read(getClass().getResource("/image/ic2.png"));
    //    } catch (IOException ex) {
    //        Logger.getLogger(FrontEnd.class.getName()).log(Level.SEVERE, null, ex);
    //    }
               
              // Image image = ImageIO.read(getClass().getResource("/images/icon.png"));
               //Image i;
            //   i=new ImageIcon(ClassLoader.getSystemResource("/icon.ico")).getImage();
    //   frontEnd.setIconImage(i); 
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton DeleteFrontEnd;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton INSERT;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton RefreshFontEnd;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
