/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DeleteFromDatabase;

import createDatabase.DatabaseExistence;
import createDatabase.GetDataFromDatabase;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author faysal
 */
public class DeletePanelFrontEnd extends javax.swing.JFrame {

    /**
     * Creates new form DeletePanelFrontEnd
     */
    
    DatabaseExistence dbed=new DatabaseExistence();
    
    DeleteFromDB dfd=new DeleteFromDB();
    
    GetDataFromDatabase gdfd=new GetDataFromDatabase();
    
    public DeletePanelFrontEnd() {
        initComponents();
        
        if(dbed.dbExist()){
    
        setList objsetlist=new setList();
        
        DeleteJList.setModel(objsetlist.deleteSetList());
        
    }
    else
    {
    JOptionPane.showMessageDialog(rootPane, "NO DATABASE !", "ERROR !", JOptionPane.ERROR_MESSAGE);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeleteJList = new javax.swing.JList();
        Delete = new javax.swing.JButton();
        DeleteAll = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Item");
        setIconImage(new ImageIcon(getClass().getResource("/icons/icon2.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<~ Select Item To Delete ~>");

        DeleteJList.setBackground(new java.awt.Color(153, 153, 153));
        DeleteJList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DeleteJList.setForeground(new java.awt.Color(0, 0, 102));
        DeleteJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(DeleteJList);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 0, 51));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        DeleteAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteAll.setForeground(new java.awt.Color(204, 0, 51));
        DeleteAll.setText("DELETE ALL");
        DeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Refresh.setForeground(new java.awt.Color(153, 153, 0));
        Refresh.setText("REFRESH");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
       String getWebAdd[]= gdfd.getWNFromDB();
                int lengthofid= gdfd.totalID(getWebAdd);
        
      if(lengthofid!=0){
          if(!DeleteJList.isSelectionEmpty()){
       
          int convalue= JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete that item?", "Delete Confirmation ?", JOptionPane.YES_NO_OPTION);
        
       
                if(convalue==0){
                        String getSelectedValue= (String)DeleteJList.getSelectedValue();
                        System.out.println("Selected item: "+getSelectedValue);
         
                        dfd.deleteItem(getSelectedValue);
                }
           }
          else
          {
          JOptionPane.showMessageDialog(rootPane, "Sorry.. You have to select one item to delete..!", "No Selection!", JOptionPane.WARNING_MESSAGE);
          }
        }
      else
      {
          JOptionPane.showMessageDialog(rootPane, "Sorry.. there is no item..to delete!", "Error no item !", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_DeleteActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        
        if(dbed.dbExist()){
    
        setList objsetlist=new setList();
        
        DeleteJList.setModel(objsetlist.deleteSetList());
        
    }
    else
    {
    JOptionPane.showMessageDialog(rootPane, "NO DATABASE !", "ERROR !", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_RefreshActionPerformed

    private void DeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllActionPerformed
        
        String getWebAdd[]= gdfd.getWNFromDB();
                int lengthofid= gdfd.totalID(getWebAdd);
        
      if(lengthofid!=0){  
                          int convalue= JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete ALL item?", "Delete Confirmation ?", JOptionPane.YES_NO_OPTION);
        
                    if(convalue==0){
                                 dfd.deleteAllItem();
                                    }
       
            }
       else
      {
          JOptionPane.showMessageDialog(rootPane, "Sorry.. there is no item.. to delete !", "Error no item !", JOptionPane.ERROR_MESSAGE);
      }
      
      
    }//GEN-LAST:event_DeleteAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePanelFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePanelFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePanelFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePanelFrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        DeletePanelFrontEnd objectDPFE=new DeletePanelFrontEnd();
        
        objectDPFE.setVisible(true);
        objectDPFE.setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton DeleteAll;
    private javax.swing.JList DeleteJList;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
